create extension if not exists "pg_cron" with schema "pg_catalog";

create extension if not exists "pg_net" with schema "extensions";

create schema if not exists "pgmq";

create extension if not exists "pgmq" with schema "pgmq";

create schema if not exists "pgmq_public";

alter table "public"."bets" drop constraint "bets_bet_prize_id_fkey";


  create table "public"."draw_results_logs" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "status" character varying not null,
    "draw_result_id" bigint not null,
    "created_by" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
      );


alter table "public"."draw_results_logs" enable row level security;

alter table "public"."bet_prizes" add column "super_jackpot" boolean not null default false;

alter table "public"."bet_prizes" add column "super_jackpot_multiplier" real;

alter table "public"."bets" drop column "bet_prize_id";

alter table "public"."bets" add column "bettor_name" character varying not null;

alter table "public"."bets" add column "created_by" uuid not null;

alter table "public"."bets" add column "is_free_bet" boolean not null default false;

alter table "public"."bets" add column "is_return_bet" boolean not null default false;

alter table "public"."bets" add column "is_super_jackpot" boolean not null default false;

alter table "public"."bets" add column "prize_amount" integer;

alter table "public"."bets" alter column "agent_id" drop default;

alter table "public"."bets" alter column "bet_type_id" drop default;

alter table "public"."bets" alter column "bet_type_id" drop not null;

alter table "public"."lotto_types" alter column "max_number" set data type integer using "max_number"::integer;

alter table "public"."lotto_types" alter column "min_number" set data type integer using "min_number"::integer;

alter table "public"."lotto_types" alter column "number_of_digits" set data type integer using "number_of_digits"::integer;

CREATE UNIQUE INDEX draw_results_logs_pkey ON public.draw_results_logs USING btree (id);

alter table "public"."draw_results_logs" add constraint "draw_results_logs_pkey" PRIMARY KEY using index "draw_results_logs_pkey";

alter table "public"."draw_results_logs" add constraint "draw_results_logs_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) not valid;

alter table "public"."draw_results_logs" validate constraint "draw_results_logs_created_by_fkey";

alter table "public"."draw_results_logs" add constraint "draw_results_logs_draw_result_id_fkey" FOREIGN KEY (draw_result_id) REFERENCES public.draw_results(id) not valid;

alter table "public"."draw_results_logs" validate constraint "draw_results_logs_draw_result_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION pgmq_public.archive(queue_name text, message_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
  begin
      return
      pgmq.archive(
          queue_name := queue_name,
          msg_id := message_id
      );
  end;
  $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.delete(queue_name text, message_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
  begin
      return
      pgmq.delete(
          queue_name := queue_name,
          msg_id := message_id
      );
  end;
  $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.pop(queue_name text)
 RETURNS SETOF pgmq.message_record
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
  begin
      return query
      select *
      from pgmq.pop(
          queue_name := queue_name
      );
  end;
  $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.read(queue_name text, sleep_seconds integer, n integer)
 RETURNS SETOF pgmq.message_record
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
  begin
      return query
      select *
      from pgmq.read(
          queue_name := queue_name,
          vt := sleep_seconds,
          qty := n , conditional := '{}'::jsonb
      );
  end;
  $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.send(queue_name text, message jsonb, sleep_seconds integer DEFAULT 0)
 RETURNS SETOF bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
  begin
      return query
      select *
      from pgmq.send(
          queue_name := queue_name,
          msg := message,
          delay := sleep_seconds
      );
  end;
  $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.send_batch(queue_name text, messages jsonb[], sleep_seconds integer DEFAULT 0)
 RETURNS SETOF bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
  begin
      return query
      select *
      from pgmq.send_batch(
          queue_name := queue_name,
          msgs := messages,
          delay := sleep_seconds
      );
  end;
  $function$
;

grant delete on table "public"."draw_results_logs" to "anon";

grant insert on table "public"."draw_results_logs" to "anon";

grant references on table "public"."draw_results_logs" to "anon";

grant select on table "public"."draw_results_logs" to "anon";

grant trigger on table "public"."draw_results_logs" to "anon";

grant truncate on table "public"."draw_results_logs" to "anon";

grant update on table "public"."draw_results_logs" to "anon";

grant delete on table "public"."draw_results_logs" to "authenticated";

grant insert on table "public"."draw_results_logs" to "authenticated";

grant references on table "public"."draw_results_logs" to "authenticated";

grant select on table "public"."draw_results_logs" to "authenticated";

grant trigger on table "public"."draw_results_logs" to "authenticated";

grant truncate on table "public"."draw_results_logs" to "authenticated";

grant update on table "public"."draw_results_logs" to "authenticated";

grant delete on table "public"."draw_results_logs" to "service_role";

grant insert on table "public"."draw_results_logs" to "service_role";

grant references on table "public"."draw_results_logs" to "service_role";

grant select on table "public"."draw_results_logs" to "service_role";

grant trigger on table "public"."draw_results_logs" to "service_role";

grant truncate on table "public"."draw_results_logs" to "service_role";

grant update on table "public"."draw_results_logs" to "service_role";


  create policy "Create Policy"
  on "public"."draw_results"
  as permissive
  for insert
  to public
with check ((((auth.jwt() -> 'user_metadata'::text) -> 'permissions'::text) @> '["Add Results"]'::jsonb));



  create policy "Update Policy"
  on "public"."draw_results"
  as permissive
  for update
  to public
using ((((auth.jwt() -> 'user_metadata'::text) -> 'permissions'::text) @> '["Edit Results"]'::jsonb));



  create policy "Create Policy"
  on "public"."draw_results_logs"
  as permissive
  for insert
  to public
with check ((((auth.jwt() -> 'user_metadata'::text) -> 'permissions'::text) @> '["Add Results"]'::jsonb));



  create policy "Update Policy"
  on "public"."draw_results_logs"
  as permissive
  for update
  to public
using ((((auth.jwt() -> 'user_metadata'::text) -> 'permissions'::text) @> '["Edit Results"]'::jsonb));



  create policy "View Policy"
  on "public"."draw_results_logs"
  as permissive
  for select
  to public
using ((((auth.jwt() -> 'user_metadata'::text) -> 'permissions'::text) @> '["View Results"]'::jsonb));



  create policy "Enable insert for authenticated users only"
  on "storage"."buckets"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable insert for authenticated users only"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Give users authenticated access to folder 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = 'private'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give users authenticated access to folder 1oj01fe_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = 'private'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give users authenticated access to folder 1oj01fe_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = 'private'::text) AND (auth.role() = 'authenticated'::text)));



